name: Deploy ALMWorkshop

on:
  workflow_run:
    workflows: ["Pack"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    environment: production
    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflows: pack-solution.yml
          name: packed-solution
      - uses: microsoft/powerplatform-actions/import-solution@v0
        with:
          environment-url: https://orgdc18e992.crm3.dynamics.com/
          user-name: ${{ secrets.USERNAME }}
          user-secret: ${{ secrets.PASSWORD }}
          solution-file: ALMWorkshop.zip
